# Generated by Django 4.2.4 on 2023-08-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("source", models.CharField(max_length=100)),
                ("editor", models.CharField(max_length=100)),
                ("keywords", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("imgurl", models.TextField()),
                ("views", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("favorites", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.news"
                    ),
                ),
            ],
        ),
    ]
