# Generated by Django 4.2.4 on 2023-09-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_comment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="local_img",
            field=models.TextField(blank=True),
        ),
    ]
